favicon: null
name: tj
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 0.4874552
  rhythmicContrast: 0.8189964
  brandColors:
    - '#000000'
    - '#E3D1BB'
    - '#27292A'
    - '#A68A77'
    - '#795F55'
  lightness: 1
typography_spectrum: 0.4802867
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3405018
analytics:
  twitter: null
  google: null
  facebook: null
